'use strict';

import axios from 'axios';
import pino from 'pino';

const log = pino({ 
  level: process.env.LOG_LEVEL || 'info',
  name: 'phoenix-slack-notifier'
});

const SLACK_WEBHOOK_URL = process.env.PHOENIX_SLACK_WEBHOOK_URL;

const SEVERITY_EMOJI = { P1: ':red_circle:', P2: ':large_yellow_circle:', P3: ':large_blue_circle:' };
const CONFIDENCE_EMOJI = { HIGH: ':white_check_mark:', MEDIUM: ':large_yellow_circle:', LOW: ':warning:' };


export async function postPhoenixIncident(service, rca, remediationSummary) {
  if (!SLACK_WEBHOOK_URL) {
    log.warn('PHOENIX_SLACK_WEBHOOK_URL not set — skipping notification');
    return;
  }

  const sev = rca.severity || 'P2';
  const category = rca.rootCause?.category || 'UNKNOWN';
  const confidence = rca.rootCause?.confidence || 'LOW';

  const blocks = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `${SEVERITY_EMOJI[sev]} Phoenix Mesh: ${rca.incidentTitle}`,
        emoji: true,
      },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Service*\n\`${service}\`` },
        { type: 'mrkdwn', text: `*Severity*\n${sev}` },
        { type: 'mrkdwn', text: `*Category*\n${category}` },
        { type: 'mrkdwn', text: `*Confidence*\n${CONFIDENCE_EMOJI[confidence]} ${confidence}` },
      ],
    },
    { type: 'divider' },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Root Cause Analysis*\n${rca.rootCause?.summary || 'N/A'}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Evidence Points*\n${(rca.rootCause?.evidence || []).map(e => `• ${e}`).join('\n')}`,
      },
    },
    { type: 'divider' },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Automated Remediation Status*\n${remediationSummary}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Remediation Assessment*\n${rca.autoRemediationAssessment?.wasAppropriate ? ':white_check_mark: Appropriate' : ':warning: Manual Review Needed'} — ${rca.autoRemediationAssessment?.explanation || ''}`,
      },
    },
  ];
//recomendations (top)
  if (rca.recommendations?.length > 0) {
    blocks.push({ type: 'divider' });
    const recText = rca.recommendations
      .slice(0, 3)
      .map(r => `• *[${r.priority}]* ${r.action}\n  _${r.rationale}_`)
      .join('\n\n');
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Phoenix Engineering Recommendations*\n${recText}` },
    });
  }

  // Incident Timeline
  if (rca.timeline?.length > 0) {
    blocks.push({ type: 'divider' });
    const timelineText = rca.timeline
      .slice(0, 5)
      .map(t => `\`${t.ts}\` ${t.event}`)
      .join('\n');
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Timeline*\n${timelineText}` },
    });
  }

  blocks.push({
    type: 'context',
    elements: [{
      type: 'mrkdwn',
      text: `:fire: Generated by Phoenix Mesh Control Plane | ${new Date().toISOString()}`,
    }],
  });

  try {
    await axios.post(SLACK_WEBHOOK_URL, { blocks }, { timeout: 5000 });
    log.info({ service }, 'Phoenix Mesh: Incident report dispatched to Slack');
  } catch (err) {
    log.error({ err: err.message }, 'Phoenix Mesh: Failed to dispatch Slack notification');
  }
}
